services:

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: demographics
      MYSQL_USER: demographics
      MYSQL_PASSWORD: demographics
    volumes:
      - db-data:./database

  jupyterlab:
    build: .
    image: jupyterlab-test-img
    container_name: jupyterlab-abm
    working_dir: /work
    volumes:
      - ../DemographicSimulation_for_Fertility_by_ABM:/work
    ports:
      - "8888:8888"
    command: jupyter-lab --ip=0.0.0.0 --allow-root --no-browser
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=demographics
      - MYSQL_USER=demographics
      - MYSQL_PASSWORD=demographics

volumes:
  db-data: