services:

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: Demographics
      MYSQL_USER: hoge
      MYSQL_PASSWORD: hoge
    volumes:
      - db-data:/var/lib/mysql
      - ./database/init/seed_AnnualTrends.sql:/docker-entrypoint-initdb.d/seed_AnnualTrends.sql
      - ./database/init/my.cnf:/etc/mysql/conf.d/my.cnf

  jupyterlab:
    build: .
    image: jupyterlab-test-img
    container_name: jupyterlab-abm
    working_dir: /work
    volumes:
      - ./src:/work
    ports:
      - "8888:8888"
    command: jupyter-lab --ip=0.0.0.0 --allow-root --NotebookApp.token=''
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=Demographics
      - MYSQL_USER=hoge
      - MYSQL_PASSWORD=hoge

volumes:
  db-data: